from LLMClient import LLMClient
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_initial_prompt(instruction):
    prompt = (
        "You are a RPA assistant that generates a Python script based on a user's instruction "
        "for interactions with web applications using the Playwright package.\n\n"
        f"The user's instructions are: {instruction}\n\n"
        "IMPORTANT: The script should follow these rules:\n"
        "1. Use `from playwright.sync_api import sync_playwright` (synchronous API)\n"
        "2. Use standard synchronous Python (no async/await)\n"
        "3. Do not use try/catch blocks\n"
        "4. The script should be self-contained with all necessary imports\n"
        "5. The script should be executable directly\n\n"
        "Only return the proposed python script."
    )
    return prompt

def clear_directory(directory: Path):
    if not directory.exists():
        return
        
    for item in directory.iterdir():
        if item.is_file():
            item.unlink()
        elif item.is_dir():
            clear_directory(item)
    
    if directory.exists():
        directory.rmdir()

import sys
import os
from pathlib import Path

def create_tracked_script(original_script_path, output_script_path):
    with open(original_script_path, 'r', encoding='utf-8') as f:
        original_content = f.read()
    
    tracking_code = """import sys
import traceback
import os
from pathlib import Path
from io import StringIO
from contextlib import redirect_stdout, redirect_stderr

def setup_tracking():
    script_dir = Path(__file__).parent
    output_file = script_dir / 'output.txt'
    error_file = script_dir / 'errorMessage.txt'
    
    output = StringIO()
    error_output = StringIO()
    
    sys.stdout = output
    sys.stderr = error_output
    
    return output, error_output, output_file, error_file

def save_outputs(output, error_output, output_file, error_file, error=None):
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("=== STDOUT ===")
        f.write(output.getvalue())
        f.write("=== STDERR ===")
        f.write(error_output.getvalue())
    
    if error:
        with open(error_file, 'w', encoding='utf-8') as f:
            f.write(f"Error: {str(error)}")
            f.write("=== STDOUT ===")
            f.write(output.getvalue())
            f.write("=== STDERR ===")
            f.write(error_output.getvalue())
            f.write("=== TRACEBACK ===")
            f.write(traceback.format_exc())

output, error_output, output_file, error_file = setup_tracking()

"""

    modified_content = tracking_code + "\n" + original_content

    modified_content += """

if __name__ == "__main__":
    try:
        # Call the original script's main function if it exists
        if 'main' in locals() and callable(main):
            main()
        save_outputs(output, error_output, output_file, error_file)
    except Exception as e:
        save_outputs(output, error_output, output_file, error_file, e)
        raise  # Re-raise the exception after saving the error
"""
    print(modified_content)
    print(output_script_path)
    with open(output_script_path, 'w', encoding='utf-8') as f:
        f.write(modified_content)

def main():
    bot_name = input("Enter name for bot: ")
    output_directory = Path(f"data/{bot_name}")
    clear_directory(output_directory)
    output_directory.mkdir(parents = True)

    user_instruction = input("Enter your instruction: ")
    prompt = generate_initial_prompt(user_instruction)

    llmClient = LLMClient()
    llm_response = llmClient.send_prompt(prompt)
    llm_response_content = llm_response["choices"][0]["message"]["content"]

    logger.info(f"Generated content length: {len(llm_response_content)} characters")
    logger.info(f"Generated content preview: {llm_response_content[:200]}...")

    if '```python' in llm_response_content:
        parts = llm_response_content.split('```python')
        if len(parts) < 2:
            raise ValueError("Could not find closing code block marker after ```python")
        script = parts[1].split('```')[0].strip()
    elif '```' in llm_response_content:
        parts = llm_response_content.split('```')
        if len(parts) < 2:
            raise ValueError("Could not find closing code block marker after ```")
        script = parts[1].strip()
        if script.startswith('python\n'):
            script = script[7:].strip()
    else:
        script = llm_response_content.strip()

    if not script:
        raise ValueError("No code was generated by the LLM")

    successCriteria = input("Enter success criteria for instructions: ")

    iteration_filepath = output_directory / "iteration1"
    iteration_filepath.mkdir(parents = True, exist_ok = True)
    with open(iteration_filepath / "scriptUnmodified.py", "w") as f:
        f.write(script)
    with open(iteration_filepath / "prompt.txt", "w") as f:
        f.write(prompt)
    with open(iteration_filepath / "successCriteria.txt", "w") as f:
        f.write(successCriteria)

    create_tracked_script(iteration_filepath / "scriptUnmodified.py", iteration_filepath / "script.py")

    logger.info(f"Script generated. To run, enter: python {iteration_filepath}\\script.py")

main()