from LLMClient import LLMClient
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_initial_prompt(instruction):
    prompt = (
        "You are a RPA assistant that generates a Python script based on a user's instruction "
        "for interactions with web applications using the Playwright package.\n\n"
        f"The user's instructions are: {instruction}\n\n"
        "IMPORTANT: The script should follow these rules:\n"
        "1. Use `from playwright.sync_api import sync_playwright` (synchronous API)\n"
        "2. Use standard synchronous Python (no async/await)\n"
        "3. Do not use try/catch blocks\n"
        "4. The script should be self-contained with all necessary imports\n"
        "5. The script should be executable directly\n\n"
        "Only return the proposed python script."
    )

bot_name = input("Enter name for bot: ")
output_directory = Path(f"data/{bot_name}")
output_directory.mkdir(parents = True, exist_ok = False)

user_instruction = input("Enter your instruction: ")
prompt = generate_initial_prompt(user_instruction)

llmClient = LLMClient()
llm_response = llmClient.send_prompt(prompt)
llm_response_content = llm_response["choices"][0]["message"]["content"]

logger.info(f"Generated content length: {len(llm_response_content)} characters")
logger.info(f"Generated content preview: {llm_response_content[:200]}...")

if '```python' in llm_response_content:
    parts = llm_response_content.split('```python')
    if len(parts) < 2:
        raise ValueError("Could not find closing code block marker after ```python")
    script = parts[1].split('```')[0].strip()
elif '```' in llm_response_content:
    parts = llm_response_content.split('```')
    if len(parts) < 2:
        raise ValueError("Could not find closing code block marker after ```")
    script = parts[1].strip()
    if script.startswith('python\n'):
        script = script[7:].strip()
else:
    script = llm_response_content.strip()

if not python_script:
    raise ValueError("No code was generated by the LLM")

iteration_filepath = output_directory / "iteration1"
iteration_filepath.mkdir(parents = True, exist_ok = False)
with open(iteration_filepath / "scriptUnmodified.py", "w") as f:
    f.write(script)
with open(iteration_filepath / "prompt.txt", "w") as f:
    f.write(prompt)

#Create modified script


logger.info(f"Script generated. To run, enter: python {iteration_filepath}/script.py")