from llm_client import LLMClient
import logging
from pathlib import Path
from script_tracking import create_tracked_script

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_script(iteration_filepath, user_instruction, success_criteria, prompt):
    iteration_filepath.mkdir(parents = True, exist_ok = True)
    with open(iteration_filepath / "prompt.txt", "w", encoding="utf-8") as f:
        f.write(prompt)
    with open(iteration_filepath / "successCriteria.txt", "w", encoding="utf-8") as f:
        f.write(success_criteria)
    with open(iteration_filepath / "instruction.txt", "w", encoding="utf-8") as f:
        f.write(user_instruction)
    
    llm_client = LLMClient()
    llm_response = llm_client.send_prompt(prompt, temperature = 0.4)
    llm_response_content = llm_response["choices"][0]["message"]["content"]

    with open(iteration_filepath / "fullResponse.txt", "w", encoding="utf-8") as f:
        f.write(str(llm_response))
    
    with open(iteration_filepath / "responseContent.txt", "w", encoding="utf-8") as f:
        f.write(str(llm_response_content))

    logger.info(f"Generated content length: {len(llm_response_content)} characters")
    logger.info(f"Generated content preview: {llm_response_content[:200]}...")

    if '```python' in llm_response_content:
        parts = llm_response_content.split('```python')
        if len(parts) < 2:
            raise ValueError("Could not find closing code block marker after ```python")
        script = parts[1].split('```')[0].strip()
    elif '```' in llm_response_content:
        parts = llm_response_content.split('```')
        if len(parts) < 2:
            raise ValueError("Could not find closing code block marker after ```")
        script = parts[1].strip()
        if script.startswith('python\n'):
            script = script[7:].strip()
    else:
        script = llm_response_content.strip()

    if not script:
        raise ValueError("No code was generated by the LLM")
        
    with open(iteration_filepath / "scriptUnmodified.py", "w", encoding="utf-8") as f:
        f.write(script)

    create_tracked_script(iteration_filepath / "scriptUnmodified.py", iteration_filepath / "script.py")

    logger.info(f"Script generated. To run, enter: python {iteration_filepath}\\script.py")